### ISSUE TITLE
how to use devServer?

### ISSUE THREAD

**Issue by sky-chy** [shuidi-fed/vapper#106]
I read your website（ https://vapperjs.org/zh/introduction.html ）It's very useful vapper.config.js File, but I can't see that this file supports devserver, because I need to request data across domains. My project is Vue For the project created by cli4, the Vue version is 2.6.12. How can I solve the cross domain problem vue.config.js File, I know how to solve it, but in the vapper.config.js I don't know what to do with this file

**Comment by auven** [comment]
vapper/plugins/api-proxy.js
```js
const { createProxyMiddleware } = require('http-proxy-middleware')

module.exports = api => {
  if (process.env.VAPPER_ENV === 'development') {
    api.use(
      createProxyMiddleware('/dev-api', {
        target: 'http://www.xxxx.com',
        changeOrigin: true,
        pathRewrite: {
          ['^/dev-api']: ''
        }
      })
    )
  }
}
```

vapper.config.js
```js
const apiProxy = require('./vapper/plugins/api-proxy')

module.exports = {
  plugins: [apiProxy]
  ...
}
```

**Comment by sky-chy** [comment]
I use nginx to deal with this cross domain problem, but thank you for your answer
