### ISSUE TITLE
demo跑不起来，是不再开源了吗？？

### ISSUE THREAD

**Issue by paddylives** [shuidi-fed/vapper#115]
### 使用[vapper-vue-cli-4-example](https://github.com/shuidi-fed/vapper-vue-cli-4-example)下载后，***yarn**** 下依赖报错
![image](https://user-images.githubusercontent.com/75835983/107174436-cef88280-69fc-11eb-8079-934b9b0820cc.png)

### 使用 ***npm i*** 下载依赖
![image](https://user-images.githubusercontent.com/75835983/107174685-68c02f80-69fd-11eb-8cb9-9b848e8f65c2.png)
![image](https://user-images.githubusercontent.com/75835983/107174713-7bd2ff80-69fd-11eb-8d89-1a83fa42052d.png)
### 本地版本说明：
windows 10 专业版
node 14.15.1
npm 6.14.8
yarn 1.22.10

**Comment by tcstory** [comment]
原作者好像跳槽到字节跳动....... 所以大家还是自食其力吧

**Comment by zhaoyunchong** [comment]
太扯了 看好这个项目  哎奈何没办法呢

**Comment by paddylives** [comment]
关了关了。作者不做了，还是用nuxtJS吧

**Comment by zhangyuang** [comment]
vapper不维护的话新同学可以看看这个SSR框架。同时支持React/Vue SSR，从第一版到现在已经维护3年了。
https://github.com/ykfe/ssr
