### ISSUE TITLE
与nuxt对比的优缺点

### ISSUE THREAD

**Issue by zhangyuang** [shuidi-fed/vapper#13]
希望能出一个章节阐述一下与一些竞品例如nuxt.js的不同之处以及优缺点
看插件机制似乎与beidou的思想类似，希望能来个全方位对比

**Comment by HcySunYang** [comment]
Also, In fact, we deliberately avoided comparing with any existing frameworks. We explicitly showed the features of Vapper here https://vapperjs.org/introduction.html#necessary-webpack-configuration, which I think is enough for the user to identify which framework to use. But for Chinese users, there is also an article here https://zhuanlan.zhihu.com/p/86246776.
