### ISSUE TITLE
How to customize root instance in vapper？

### ISSUE THREAD

**Issue by ChenpDean** [shuidi-fed/vapper#14]
I want to customize root instance(refers to App.vue in a Vue.js program) in some cases, but I can't find how to implement it in nuxt.So I want to know can I implement this function in vapper?Thx

**Comment by HcySunYang** [comment]
Yes, you can completely customize it, just like developing a SPA app. You can read this to learn about the entry file: https://vapperjs.org/entry.html#entry-file

**Comment by ChenpDean** [comment]
Thx，It's just what I want
