### ISSUE TITLE
Support vue-cli version 4

### ISSUE THREAD

**Issue by chanlito** [shuidi-fed/vapper#22]
<img width="1028" alt="Screen Shot 2019-11-17 at 10 52 00 AM" src="https://user-images.githubusercontent.com/15667259/69002787-7c7b0400-0928-11ea-9e6a-21d2ab45f3ec.png">

**Comment by HcySunYang** [comment]
Oh, currently only compatible with version 3, we will support version 4 as soon as possible.

**Comment by chanlito** [comment]
@HcySunYang so I looked into the error again and removed `@vue/cli-plugin-pwa` and it works.

**Comment by HcySunYang** [comment]
Ah, that’s great.

**Comment by HcySunYang** [comment]
It can be determined that vapper can play well with Vue CLI4, here is a simple example that works correctly: https://github.com/shuidi-fed/vapper-vue-cli-4-example

**Comment by marcelohmdias** [comment]
Hi @HcySunYang

Will the PWA plugin be supported?

Congratulations for the work.
