### ISSUE TITLE
在@0.13.1中仍然存在路径问题

### ISSUE THREAD

**Issue by bromiao** [shuidi-fed/vapper#23]
![image](https://user-images.githubusercontent.com/19767083/69004496-12298a00-094f-11ea-92ca-66f481c75ff1.png)
![image](https://user-images.githubusercontent.com/19767083/69004522-95e37680-094f-11ea-8498-5303f29313f3.png)

文件名写死了，导致 import defaultEnhanceClientApp from '../../../../../src/defaultEnhanceClientApp.js'

**Comment by bromiao** [comment]
另外在数据预取拿到 结果后执行了浏览器环境下的逻辑，该怎么处理呢

**Comment by HcySunYang** [comment]
@bromiao 
问题一：更新到 0.13.2 版本。
问题二：在 nodejs 中不能执行浏览器的 API，需要想办法解决，如果是组件不兼容 SSR，那么可以使用 <ClientOnly> 组件包裹它们。其他情况可以增加判断来避免，例如 `if (typeof window !== 'undefined') `之类的

**Comment by bromiao** [comment]
![image](https://user-images.githubusercontent.com/19767083/69008585-fe017f00-0986-11ea-8a88-a826a6777415.png)

使用ClientOnly包裹后，还是报错，也设置了相应的ssr为false,也没用，怎么规避第三方插件带来的影响
![image](https://user-images.githubusercontent.com/19767083/69008627-841dc580-0987-11ea-826a-afb89489a193.png)
我是这样引用的。。。。。头大，我该在什么地方做环境判断，麻烦大佬指点。。。
