### ISSUE TITLE
遗留问题。。。

### ISSUE THREAD

**Issue by bromiao** [shuidi-fed/vapper#24]
![image](https://user-images.githubusercontent.com/19767083/69008585-fe017f00-0986-11ea-8a88-a826a6777415.png)

使用ClientOnly包裹后，还是报错，也设置了相应的ssr为false,也没用，怎么规避第三方插件带来的影响
![image](https://user-images.githubusercontent.com/19767083/69008627-841dc580-0987-11ea-826a-afb89489a193.png)
我是这样引用的。。。。。头大，我该在什么地方做环境判断，麻烦大佬指点。。。

_Originally posted by @bromiao in https://github.com/shuidi-fed/vapper/issues/23#issuecomment-554749869_

**Comment by HcySunYang** [comment]
看来我们需要编写 SSR 编码的注意事项来指导用户。我们会在最近今天编写相关教程，请稍后。

**Comment by HcySunYang** [comment]
但是可以给你一个临时的变通方案，这个问题的本质是 Banner.vue 中 import 了 finger-mover，finger-mover 是不兼容 ssr 的。你可以创建一个 Banner2.vue 组件，这个组件可以什么都渲染，后者简单的渲染一个空 <div>。然后在 index.vue 组件中像如下这样引用 banner 组件：
```js
let Banner = null
if (typeof window !== 'undefined') {
  // 浏览器中
  Banner = () => import('./Banner.vue')
} else {
  // 在 nodejs 中
  Banner = () => import('./Banner2.vue')
}
```
**`<ClientOnly>` 组件仍然要使用**
