### ISSUE TITLE
请求支持路由全路径~

### ISSUE THREAD

**Issue by hujin0618** [shuidi-fed/vapper#26]
vue路由在被服务端渲染后，会被执行成`<a href="/ccc">`
但由于我们需求上存在基地址是包含二级域名的，相对路径对seo不是很友好。
可否直接渲染出`<a href="http://a.bbbb.com/ccc">` ?

**Comment by HcySunYang** [comment]
这个问题貌似和服务端渲染没关系，你要想渲染出来的内容是你所期望的，那在写代码的时候就写成那个样子即可。你可以写完整的路径，这样就会渲染出完整的路径；否则 vue ssr 怎么知道完整的地址是什么呢？

**Comment by hujin0618** [comment]
当我填入完成的路径后, 如 `to="a.bbb.com/ccc"`，实际渲染后，href指向的是`http://a.bbb.com/a.bbb.com/ccc`，这非常苦恼。

**Comment by hujin0618** [comment]
> 这个问题貌似和服务端渲染没关系，你要想渲染出来的内容是你所期望的，那在写代码的时候就写成那个样子即可。你可以写完整的路径，这样就会渲染出完整的路径；否则 vue ssr 怎么知道完整的地址是什么呢？

**Comment by HcySunYang** [comment]
这个场景你应该使用 `<a>` 标签代替 `<router-link>`

**Comment by hujin0618** [comment]
嗯，直接使用`<a>`是可以的，不过这改动量有点大。
route上能否设置个基本路径baseurl什么的，让它自己加上？

**Comment by HcySunYang** [comment]
只有需要vue router控制的跳转才应该用router-link，你的场景使用router-link是不合理的。如果一定要这么用，那么这属于vue router的范畴，vapper帮不到什么忙。

**Comment by hujin0618** [comment]
明白了
