### ISSUE TITLE
how to use pm2 to start app

### ISSUE THREAD

**Issue by breezefeng** [shuidi-fed/vapper#27]

**Comment by breezefeng** [comment]
how to  use pm2 or other procee manage tool to start or stop app

**Comment by jarone** [comment]
hi， @breezefeng  

Actually any process management tool is based on `node xxx.js`. For how to create xxx.js corresponding to the web framework, please refer to: https://vapperjs.org/custom-server.html

**Comment by breezefeng** [comment]
thanks!

**Comment by panchenyu0928** [comment]
> 如何使用pm2或其他procee管理工具启动或停止应用

pm2 start npm --name <project-name> -- run start

**Comment by panchenyu0928** [comment]
> how to use pm2 or other procee manage tool to start or stop app

pm2 start npm --name project-name -- run start
