### ISSUE TITLE
render template throw error

### ISSUE THREAD

**Issue by breezefeng** [shuidi-fed/vapper#31]
![image](https://user-images.githubusercontent.com/4973944/69773203-1fefd280-11cd-11ea-8252-12bd387f9f62.png)
![image](https://user-images.githubusercontent.com/4973944/69773221-2ed68500-11cd-11ea-8bee-66e64e32bced.png)

**Comment by HcySunYang** [comment]
Please provide reproduction. the information above is not enough. 
It looks like something is wrong with `JSON.stringify`.

**Comment by breezefeng** [comment]
I use iview ui framework,is it have to config something else ?

**Comment by HcySunYang** [comment]
Did you use custom index.html? It looks like a vue-server-render's templateRender error.

**Comment by breezefeng** [comment]
yes:
![image](https://user-images.githubusercontent.com/4973944/69774174-292e6e80-11d0-11ea-8b68-3af0d1d1c64c.png)

**Comment by HcySunYang** [comment]
Please share your `vapper.config.js`.

**Comment by breezefeng** [comment]
module.exports = {
  port: 3000
}

**Comment by breezefeng** [comment]
in nuxt.js use iview.js to ssr must config,this is url:https://github.com/iview/iview/issues/1942,so vapper is it have to config too?

**Comment by HcySunYang** [comment]
Looks like an error occurred while serializing the state of the circular reference, this has nothing to do with vapper. the following reference may help you:
https://github.com/vuejs/vue/issues/6614
https://github.com/vuejs/vue/commit/44940121eef4e2df5f3cb3c21f3f468af8b336bc

> in nuxt.js use iview.js to ssr must config,this is url:[iview/iview#1942](https://github.com/iview/iview/issues/1942) vapper is it have to config too?
vapper is completely different from nuxt, you don't need to do that in vapper

**Comment by breezefeng** [comment]
I print the obj, it is this
![image](https://user-images.githubusercontent.com/4973944/69775714-92b07c00-11d4-11ea-9f63-a022d302ab32.png)
the stringify action does in your framework,I has no way to do

**Comment by breezefeng** [comment]
in serialize-javascript.js npm I replace stringify function is ok

![image](https://user-images.githubusercontent.com/4973944/69775852-179b9580-11d5-11ea-9ec5-2496b852700d.png)

**Comment by HcySunYang** [comment]
The problem is in `menu: [VueComponent]`, Maybe you can use `menu: 'ComponentName'` instead?

**Comment by breezefeng** [comment]
how to use ComponentName ? This obj is not my control

**Comment by breezefeng** [comment]
I want to know when to resolve this issue ?

**Comment by HcySunYang** [comment]
Can you use the [\<ClientOnly\>](https://vapperjs.org/injection.html#the-clientonly-component) component as a temporary workaround?

**Comment by breezefeng** [comment]
It's OK. But I hope this issue can resolved quickly.Thanks!

**Comment by HcySunYang** [comment]
Fixed, please use `@vapper/core@0.14.5`.

**Comment by breezefeng** [comment]
It's already OK.Thanks~
