### ISSUE TITLE
Any way to do server-side rendering with auth?

### ISSUE THREAD

**Issue by breezefeng** [shuidi-fed/vapper#34]

**Comment by HcySunYang** [comment]
Do it in the routing guard and maybe with the redirect?
For redirect: https://vapperjs.org/injection.html#redirect-redirect

**Comment by breezefeng** [comment]
I have still a question:how to translate cookie from client request to server?

**Comment by breezefeng** [comment]
I mean in ssr mode

**Comment by HcySunYang** [comment]
Maybe you need `@vapper/plugin-cookie`: https://vapperjs.org/using-plugin.html#vapper-plugin-cookie

**Comment by breezefeng** [comment]
year，I know. My scene is first to login and get userInfo, then use useInfo to request api to get data? Is there a better way to do this?

**Comment by HcySunYang** [comment]
You can use `res.setHeader('set-cookie', 'xx')` directly with the [fromRes](https://vapperjs.org/using-plugin.html#fromres) option of the `@vapper/plugin-cookie` plugin. In this way, subsequent operations to read cookies will carry these cookies.

How to set the `fromRes` options:

```js
// entry file
createApp.pluginRuntimeOptions = {
  cookie: { fromRes: true }
}
```
