### ISSUE TITLE
Return code 404 on notfound

### ISSUE THREAD

**Issue by thierrymichel** [shuidi-fed/vapper#37]
Hi,

First of all, thanks for the great job. 👍 
And sorry to ask question here… 😬 

Is there a way (or how can I do) to return a `404` status code if a page/route does not exists ?
I've checked the `examples/custom-error-page` but it returns a `200` code.

Thanks in advance!

**Comment by thierrymichel** [comment]
Ok, I guess I can look at some custom middleware using `before:render`… right?
Or do you see other ways?

Thanks again.

**Comment by HcySunYang** [comment]
Wait for us to add more detailed documentation in the near future. 😬

**Comment by thierrymichel** [comment]
Hi @HcySunYang,

Thanks for the answer. That's really cool (even if I started writing some plugin)
Can't wait!  👀😜👍

**Comment by HcySunYang** [comment]
Hi @thierrymichel , there is detailed documentation here: https://vapperjs.org/error-handling.html#custom-error-page. So I closed this issue.
