### ISSUE TITLE
When the head option is a function, it will cause repeated data prefetching

### ISSUE THREAD

**Issue by allowing** [shuidi-fed/vapper#39]
如题，偶然发现声明了`needSerialize: true`，客户端还是执行了`created`，然后就尝试找原因，发现是因为存在`head()`函数的原因，如果是`head: {}`静态的对象的形式，又不会重复执行

**Comment by HcySunYang** [comment]
This is really a bug

**Comment by HcySunYang** [comment]
Fixed in `@vapper/core@0.18.3`.
