### ISSUE TITLE
插件运行时机导致 createApp 时无法正常使用 $cookie

### ISSUE THREAD

**Issue by cloudcome** [shuidi-fed/vapper#53]
**Describe the bug**

```js
export default function createApp(context) {
    const { $cookie } = context;
            ^^^^^^^
            $cookie 是 undefined
// ...
```

**To Reproduce**
使用方案与[官方文档（使用插件 @vapper/plugin-cookie）](https://vapperjs.org/zh/using-plugin.html#vapper-plugin-cookie)一致

> @vapper/plugin-cookie 插件会读取 pluginRuntimeOptions.cookie 对象作为选项参数。
>
> 通过 ctx 访问 $cookie 对象：
>
> ```js
> // 入口文件
> export default function createApp (ctx) {
> ctx.$cookie.get('foo') // Read cookie named `foo`
> ctx.$cookie.set('foo', 1) // Set cookie named `foo`
> }
> 
> createApp.pluginRuntimeOptions = {
> cookie: { /* options */ }
> }
> ```

原因是在 clientEntry 执行的时候，createApp 运行在插件运行之前。

```js
import Vue from 'vue'
import { clientPlugin } from './prefetcher'
import createApp from './createApp'
import VapperError from './VapperError'
import { createClientRedirect } from './redirect'

// Dynamically generated by vapper
import enhanceApp from './.vapper/enhanceClient'

const TYPE = 'client'

Vue.use(clientPlugin)

const context = {
  pluginRuntimeOptions: createApp.pluginRuntimeOptions,
  type: TYPE
}

const rootOptions = createApp(context)
                    ^^^^^^^^^
                    在插件运行之前，这时候 context 里没有 $cookie
const { router, store } = rootOptions
context.rootOptions = rootOptions

enhanceApp(context)
```

**Comment by HcySunYang** [comment]
Use `1.0.1`.
