### ISSUE TITLE
使用 this.$$redirect() 报错

### ISSUE THREAD

**Issue by cloudcome** [shuidi-fed/vapper#54]
**Describe the bug**
使用 this.$$redirect() 报错

**To Reproduce**

```js
this.$$redirect({
    name: 'Login',
    query: {
        to: this.$route.fullPath
    }
});
```

**Screenshots**

![image](https://user-images.githubusercontent.com/3362033/72421167-f6a9f680-37ba-11ea-8538-63cd1253d5c6.png)

**Comment by HcySunYang** [comment]
Can you provide a reproduction?
Here is an example about redirects, which passed the test: https://github.com/shuidi-fed/vapper/tree/master/examples/redirect

**Comment by cloudcome** [comment]
![image](https://user-images.githubusercontent.com/3362033/72430862-5a89ea80-37ce-11ea-8c28-a18dcd923402.png)

**Comment by HcySunYang** [comment]
https://github.com/shuidi-fed/vapper/tree/master/examples/redirect
这个 demo 已经按照上图修改路径，经测试并没有发现问题。如果你仍然可以复现问题，请提供可重现的项目。

**Comment by cloudcome** [comment]
可重现项目：
<https://github.com/cloudcome/vapper-examples/tree/master/redirect>

**Comment by HcySunYang** [comment]
This is really a bug, thanks, please use `@vapper/core@^1.0.2`
