### ISSUE TITLE
ctx.$cookie 为 undefined

### ISSUE THREAD

**Issue by cloudcome** [shuidi-fed/vapper#55]
![image](https://user-images.githubusercontent.com/3362033/72431484-ecdebe00-37cf-11ea-8202-a3dd5b8886af.png)

同 #53 ，升级到 1.0.1 问题没有解决

**Comment by HcySunYang** [comment]
请提供可重现的项目，因为你的问题别人复现不了，你不提供可重现的项目，就无法得到有效的帮助。

**Comment by cloudcome** [comment]
这个问题很诡异，我是原来项目（1.0.0）的基础上升级到 1.0.1 的，但是项目运行的时候的代码还是旧的（1.0.0)，也就是说，运行的代码和实际的代码不一致。

-------------------

浏览器看到的代码：
![image](https://user-images.githubusercontent.com/3362033/72490140-46d39800-3851-11ea-8547-fa318009b25b.png)



实际项目里的代码：
![image](https://user-images.githubusercontent.com/3362033/72490145-4f2bd300-3851-11ea-8031-1fd5abe3b51e.png)


删除 node_modules 之后重新安装模块，没有出现上述错误了，但有了新的错误：

![image](https://user-images.githubusercontent.com/3362033/72490346-ff99d700-3851-11ea-845e-58cdaa358201.png)

**可重现项目：**
<https://github.com/cloudcome/vapper-examples/tree/master/plugin-cookie>

**Comment by HcySunYang** [comment]
Please use `@vapper/plugin-cookie@^1.0.1`
