### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method

### ISSUE THREAD

**Issue by bromiao** [shuidi-fed/vapper#57]
![image](https://user-images.githubusercontent.com/19767083/72531333-33094f80-38ac-11ea-8867-e500e6c79667.png)

搜索一番后，疑似和ssr有关，参见[@vuepress-theme-indigo-material#5](https://github.com/zhhlwd/vuepress-theme-indigo-material/issues/5)

**Comment by bromiao** [comment]
临时解决方案--------https://github.com/nuxt/nuxt.js/issues/1552#issuecomment-393236698

**Comment by HcySunYang** [comment]
@bromiao Can you share the details of your problem and how did you solve it? Thanks.

**Comment by bromiao** [comment]
在dev下，会出现这样的提示

![image](https://user-images.githubusercontent.com/19767083/72612775-af616880-3968-11ea-8c29-c4c514fb2566.png)

打包后，node启动一个服务文件，刷新页面就会报issue中的错误

**Comment by bromiao** [comment]
> @bromiao Can you share the details of your problem and how did you solve it? Thanks.

@HcySunYang 
我在dev下，刷新页面会报如下提示

![image](https://user-images.githubusercontent.com/19767083/72613180-dbc9b480-3969-11ea-9ee5-ccf8ed157de8.png)

打包后，node启动一个服务文件，刷新页面就会报issue中的错误，导致应用崩溃
