### ISSUE TITLE
vue.config > publichPath 和 (new Router).base 导致 ssr 404 错误

### ISSUE THREAD

**Issue by cloudcome** [shuidi-fed/vapper#58]
**Describe the bug**
vue.config > publichPath 和 (new Router).base 导致 ssr 404 错误

**To Reproduce**

1. 设置 vue.config 里的 `publichPath` 为 `/abc`
2. 设置 new Router 里的 `base` 参数为 `/abc`
3. 启动自定义 server 为开发模式，`ssr` 默认为 `true`
4. 访问 http://localhost:4000/abc
5. 查看源代码，发现 ssr 并未生效，并且在控制台打印出错误消息

```
debug Server rendering encountered an error: Error [VapperError]: Page Not Found
    at new VapperError (node_modules/@vapper/core/app/VapperError.js:6:0)
    at module.exports../node_modules/@vapper/core/app/serverEntry.js.__webpack_exports__.default (node_modules/@vapper/core/app/serverEntry.js:71:0)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'VapperError',
  url: '/abc',
  code: 404,
  message: 'Page Not Found',
  isVapper: true
}
debug Will fall back SPA mode, url is: /abc
```

可复现工程：<https://github.com/cloudcome/vapper-examples/tree/master/custom-server>

**Comment by HcySunYang** [comment]
Please use: `@vapper/core@^1.0.3`.

**Comment by cloudcome** [comment]
![image](https://user-images.githubusercontent.com/3362033/72704302-56294d00-3b93-11ea-84bd-630c582ca90e.png)

这几行日志是什么鬼？

还是有问题：

1. `http://localhost:4000/abc` 👌
2. `http://localhost:4000/abc/` 🙅（注意末尾的斜杆）

**Comment by HcySunYang** [comment]
删除掉 `vapper.config.js` 中的 `publicPath`
