### ISSUE TITLE
TypeError: t.apply is not a function

### ISSUE THREAD

**Issue by bromiao** [shuidi-fed/vapper#63]
1.在@0.x版本中序列化bug，项目中引入@0.18.4,ssr设为true的路由组件中设置needSerialize:true,打包后运行控制台出现如下错误（TypeError: t.apply is not a function）

2.升级到@1.x版本后,问题依然存在

![image](https://user-images.githubusercontent.com/19767083/73067079-a92c3880-3ee2-11ea-8f2b-8a6cc4744cb1.png)

![image](https://user-images.githubusercontent.com/19767083/73063577-0a034300-3eda-11ea-8fbb-26ac0ec5a2e5.png)

组件中代码结构大致如下
```
{
     needSerialize: true,
     async created() {
        await this.getNews('xx');
        await this.getNews('xxx');
     },
     mounted() {
         this.$root.$children[0].Bus.$emit('nav-top', this.topNav);
         this.$root.$children[0].Bus.$emit('nav-bottom', this.currNav);
     },
     methods: {
         getNews(code) {
             return this.$axios.getData(‘xxxx’).then(res => {})
         }
     }
}
```

**Comment by HcySunYang** [comment]
可以提供一个可复现的项目吗？这里有一个项目模板：https://github.com/shuidi-fed/vapper-vue-cli-example

**Comment by bromiao** [comment]
> 可以提供一个可复现的项目吗？这里有一个项目模板：https://github.com/shuidi-fed/vapper-vue-cli-example

复现地址：[https://github.com/bromiao/vapper-example.git](https://github.com/bromiao/vapper-example.git)

进入pagetest路由页面后，控制台就报那个错误，刷新后，报dom不匹配的错误，导致页面数据未能渲染

**Comment by HcySunYang** [comment]
我看例子中的 @vapper/core 版本是 0.18.x，可以尝试一下最新版本嘛

**Comment by HcySunYang** [comment]
我提供了一个可运行的例子：https://github.com/HcySunYang/vapper-issue-63
基于你的代码进行改动，关键在于路由需要使用 history 模式。
