### ISSUE TITLE
Cannot set property '$$redirect' of undefined when migrating from v0.x to v1.x

### ISSUE THREAD

**Issue by xiamu33** [shuidi-fed/vapper#66]
![image](https://user-images.githubusercontent.com/31266885/73864285-5b1d1a80-487c-11ea-92ae-06221dad4e9e.png)

I follow the migrate guide and use [vapper-vue-cli-example](https://github.com/shuidi-fed/vapper-vue-cli-example) (the vapper v0.17.0)

yarn upgrade to v1.2.1 (and some other 1.x version, the same problem)

It's a simple example that all use default config so I only modify the `creatApp` function:
```js
  // 2. Create a app instance
  const app = new Vue({
    router,
    // This is necessary, it is for vue-meta
    head: {},
    render: h => h(App)
  })

  // 3. return
-  return { app, router }

+  return app
```
and cause the error 

then I view the source code `@vapper/core/app/creatApp.js`
```js
export default function createAppAPI (context) {
  const rootOptions = createApp(context)
  Object.assign(rootOptions, context.rootOptions)
  return rootOptions
}
```
it return a instance of Vue

and in `@vapper/core/app/serverEntry.js`
```js
  const rootOptions = createAppAPI(context) // line#29
  const { router, store, apolloProvider } = rootOptions

  // Add helpers
  router.$$redirect = createServerRedirect(context.res) // line#56
  router.$$type = TYPE
```
`router` will be `undefined` and cause the server error
and error in clinet **`Cannot read property 'beforeHooks' of undefined`**

I modify the source code `@vapper/core/app/creatApp.js` and it works
```js
-  return rootOptions

+  return rootOptions.$options
```

is it a bug or I do sth wrong between migrating?

and the example has no `store` or other plugins

**Comment by HcySunYang** [comment]
Don't use `new Vue`:
```js
const app = {
    router,
    // This is necessary, it is for vue-meta
    head: {},
    render: h => h(App)
}
```

**Comment by xiamu33** [comment]
> Don't use `new Vue`:
> 
> ```js
> const app = {
>     router,
>     // This is necessary, it is for vue-meta
>     head: {},
>     render: h => h(App)
> }
> ```

my careless, thx
