### ISSUE TITLE
Problem with `.vapper_server.js`

### ISSUE THREAD

**Issue by thierrymichel** [shuidi-fed/vapper#71]
**Describe the bug**
Hi,
Looks like [this commit](https://github.com/shuidi-fed/vapper/commit/3e6091095f48cc92af7b9907033f5cd3439c90eb) introduces a new behaviour "compiling" plugin/middleware files to `.vapper_server.js`

But id does not compile anything. 
It just copy the file content and rename it.
As I am using TypeScript I get syntax errors and unexpected tokens…

```ts
// src/inc/middlewares/resource-server.ts
// This is not valid JavaScript
export default function(ctx: any): void {
  // …
}
```
In addition, I need to git-ignore it
Thanks

**Expected behavior**
No errors, no files

**Comment by HcySunYang** [comment]
This is really a problem, thanks.  But here is a workaround: https://vapperjs.org/write-plugin.html#optional-compilation

**Comment by thierrymichel** [comment]
Perfect, works fine. Thanks a lot 🙏
