### ISSUE TITLE
自定义express server后，配置项template无效

### ISSUE THREAD

**Issue by fa-ge** [shuidi-fed/vapper#73]
**Describe the bug**
将examples中的 custom-server-express 升级到最新版本后，在vapper.config.js中增加template和port均无效，无任何报错，能正常启动访问。删掉template配置项，port就会生效。

**Comment by fa-ge** [comment]
package.json 的配置
  "dependencies": {
    "@vapper/core": "^1.3.0",
    "express": "^4.17.1",
    "vue": "^2.6.11",
    "vue-router": "^3.1.5"
  },
  "devDependencies": {
    "@vue/cli-service": "~4.2.0",
    "cross-env": "^6.0.0",
    "vue-template-compiler": "^2.6.11"
  }

**Comment by HcySunYang** [comment]
请提供可复现的工程

**Comment by fa-ge** [comment]
https://github.com/fa-ge/vapper/tree/master/examples/custom-server-express

**Comment by fa-ge** [comment]
> 请提供可复现的工程

https://github.com/fa-ge/vapper/tree/master/examples/custom-server-express

**Comment by HcySunYang** [comment]
在你的例子中，`vapper.config.js` 中需要引入 `fs` 模块：
```js
const path = require('path');
const fs = require('fs');

module.exports = {
  // default
  fallBackSpa: true,
  port: 4005,
  template: fs.readFileSync(path.resolve('./public/index.ssr.html'), 'utf-8'),
}
```

不过 `vapper` 没能展现报错信息的确是个问题，感谢反馈。

**Comment by HcySunYang** [comment]
https://github.com/shuidi-fed/vapper/commit/6f63e6ff294766323585abdb6fd1b254b84e972e
