### ISSUE TITLE
Modify server or client webpack configuration in vapper plugin

### ISSUE THREAD

**Issue by xiaoxiaoaobama** [shuidi-fed/vapper#75]
hi, I am developing the sentry plugin for vapper.

The plugin needs to distinguish between client and server builds, and then make different modifications to the webpack configuration, as follows:

```js
module.exports = (api) => {
  api.chainWebpack(config => {
    if (isClient) {
      // ...
    }

    if (!isClient) {
      // ...
    }
  })
}
```

After that, I found `process.env.VAPPER_TARGET` in the [documentation](https://vapperjs.org/zh/injection.html#process-env-vapper-target), and use it to distinguish between server-side and client-side builds in the plugin:

```js
module.exports = (api) => {
  api.chainWebpack(config => {
    if (process.env.VAPPER_TARGET === 'client') {
      // ...
    }

    if (process.env.VAPPER_TARGET === 'server') {
      // ...
    }
  })
}
```

I hope that the [Writing a plugin part](https://vapperjs.org/write-plugin.html#basic) of the document can increase the above cases, so that developers can quickly get solutions.

**Comment by HcySunYang** [comment]
Aha, it's here: https://vapperjs.org/injection.html#process-env-vapper-target.
