### ISSUE TITLE
compile enhance.template.ejs

### ISSUE THREAD

**Issue by xiaoxiaoaobama** [shuidi-fed/vapper#76]
When the clientModuleName of multiple plugins is the same, an error will be reported when parsing enhancement.template.ejs：

```js
// vapper.config.js
const myVapperPlugin = require('./testPlugin')

module.exports = {
  plugins: [
    ['@vapper/plugin-cookie'],
    [myVapperPlugin]
  ]
}
```

```js
// testPlugin.js
const path = require('path')

module.exports = (api) => {
  api.addEnhanceFile({
    needCompile: false,
    client: path.resolve(__dirname, './m.js'),
    server: path.resolve(__dirname, './m.js'),
    clientModuleName: 'cookie'
  })
}
```
Run `yarn build`, the console displays the error message, as follows:

![image](https://user-images.githubusercontent.com/26184778/75145364-c3507500-5733-11ea-8e98-a64a2811328f.png)

I think passing in the index value when compiling the enhancement.template.ejs file is a solution, for example:

```js

import cookie_0 from '../../../plugin-cookie/lib/cookie.js'

import cookie_1 from '../../../../../testPlugin/cookie.js.js'

import xx_2 from 'xx'

import xx_3 from 'xx'

export default function (options) {
  
    cookie_0(options)
  
    cookie_1(options)

    xx_2(options)

    xx_3(options)
}
```

**Comment by HcySunYang** [comment]
Maybe we can automatically generate the `clientModuleName` so that users don't need to care about it.

**Comment by HcySunYang** [comment]
Can you submit a PR for our discussion(include https://github.com/shuidi-fed/vapper/issues/77)?

**Comment by xiaoxiaoaobama** [comment]
> Maybe we can automatically generate the `clientModuleName` so that users don't need to care about it.

good idea.

**Comment by xiaoxiaoaobama** [comment]
> Can you submit a PR for our discussion(include #77)?

ok，let me try
