### ISSUE TITLE
a question about clientModuleName

### ISSUE THREAD

**Issue by xiaoxiaoaobama** [shuidi-fed/vapper#77]
When I use api.addEnhanceFile, the clientModuleName property passed in makes me confused, for example:

```js
api.addEnhanceFile ({
       needCompile: false,
       server: path.resolve (__ dirname, './sentry-server.js'),
       clientModuleName: 'sentryServer'
})
```

I want to generate a file that enhances the runtime of the server. The clientModuleName property makes me first feel that it is needed to generate the client file.

I checked the clientModuleName related code and found that this clientModuleName will be used when generating server and client files.

```js
// enhance.template.ejs
<% for (const enhanceObj of enhanceFiles) {%>
import <%-enhanceObj.clientModuleName%> from '<%-type === "client"? enhanceObj.client: enhanceObj.server%>'
<%}%>

export default function (options) {
   <% for (const enhanceObj of enhanceFiles) {%>
     <%-enhanceObj.clientModuleName%> (options)
   <%}%>
}
```

In this case, would it be more accurate to rewrite clientModuleName to moduleName?

**Comment by HcySunYang** [comment]
You are right, let's discuss it here: https://github.com/shuidi-fed/vapper/issues/76.
