### ISSUE TITLE
期望自定义 server 后，在 server 端修改时自动重启 server

### ISSUE THREAD

**Issue by cloudcome** [shuidi-fed/vapper#79]
在使用 [自定义 Server](https://vapperjs.org/zh/custom-server.html#%E8%87%AA%E5%AE%9A%E4%B9%89-server) 功能之后，很容易遇到的一个问题就是，在开发过程中经常性修改 server 端的文件。

修改之后理想期望是可以自动重启 server，而不需要整体手动重启。

**Comment by HcySunYang** [comment]
本质上这不是 vapper 要负责的内容，你可以参考已有的 nodejs 应用的开发模式，例如 pm2 等。

**Comment by cloudcome** [comment]
😑行吧，还是得自己来。
