### ISSUE TITLE
请问多个template对应多个bundle.json如何做到

### ISSUE THREAD

**Issue by fa-ge** [shuidi-fed/vapper#80]
**Describe the solution you'd like**
前端有多个独立的项目会生成服务端需要的bundle

**Comment by HcySunYang** [comment]
请提供完善的场景信息

**Comment by fa-ge** [comment]
我前端项目有很多个，a,b,c,d相互独立，但是server只有一个。server会给a,b,c,d分别分配一个路由。现在我想做ssr，前端项目我依旧想要独立，所以 a,b,c,d打包后会生成4个bundle.json。我是想多个路由可以匹配多个bundle.json，我看现在应该是不支持的。不知道有没有描述清楚

**Comment by HcySunYang** [comment]
这本质上和 vapper 的关系不大，可以从工程化层面解决。

**Comment by fa-ge** [comment]
> 这本质上和 vapper 的关系不大，可以从工程化层面解决。

可是vapper只能从配置文件配置一个template和bundle.json，对于我这样的情况就不能做了。

**Comment by HcySunYang** [comment]
可否创建多个 vapper 实例？一个项目对应一个 vapper 实例？

**Comment by fa-ge** [comment]
> 可否创建多个 vapper 实例？一个项目对应一个 vapper 实例？

可是我只想监听一个端口

**Comment by HcySunYang** [comment]
可以用 nginx 做一层代理，应该很容易配置的。或者用 nodejs 写一个，去搜索一下相关实现，应该不麻烦。

**Comment by fa-ge** [comment]
可是这就把项目搞复杂了。多了一个nginx的依赖。
