### ISSUE TITLE
Running DEV on https

### ISSUE THREAD

**Issue by mikimoresi** [shuidi-fed/vapper#86]
I would like to run the dev mode under https.
How can it be done?
Thank you

**Comment by HcySunYang** [comment]
Just like the normal Vue CLI app, even more, you can use nginx as a local proxy.

**Comment by mikimoresi** [comment]
If i set https:true in the vue.config.js, when running dev, it says "https not supported"

If i try to find the usual https flag in the "more parameters panel" in the Vue CLI UI i cannot find any https flag.

Can I know where exactely should i set the option?

Thank you

**Comment by HcySunYang** [comment]
1. Start the `vapper` server, let's say the server is running at `http://127.0.0.1:4000`.
2. Configure nginx as follows:
```
server {
      listen 443 ssl;
      listen       [::]:443;
      server_name www.foo.com;

      #ssl on;
      ssl_certificate /usr/local/etc/nginx/conf/foo.com.crt;
      ssl_certificate_key /usr/local/etc/nginx/conf/foo.com.key;

      location / {
        proxy_pass      http://127.0.0.1:4000;
      }
}
```
3. You can access the service at `https://www.foo.com`.

**Comment by mikimoresi** [comment]
I will try this approach.
Do you think a flag like the basic Vue cli UI will be available in the future?
Thank you.

**Comment by mikimoresi** [comment]
Thank you this is awesome. 
New option in vapper.config.js available:

```js
const fs = require('fs');
module.exports = {
  host: your-host',
  https:{
  	key: fs.readFileSync('/yourpath/to/certs/key.pem'),
  	cert: fs.readFileSync('/yourpath/to/certs/cert.pem'),
  }
}
```
