### ISSUE TITLE
请问如何实现动态添加路由

### ISSUE THREAD

**Issue by Wphilipp** [shuidi-fed/vapper#87]
**Is your feature request related to a problem? Please describe.**
我的需求是根据用户不同的权限分配不同的路由表.我的实现逻辑是前端有一个总的路由表,再根据服务端返回的路由list, 对总的路由表进行过滤,得到该用户可以访问的路由表.最后把这个路由表add进router实例里.请问我应该在哪个地方实现这个逻辑?

**Describe the solution you'd like**
我想到的解决方案是:将这个根据权限过滤路由表,添加路由的逻辑放到一个generateRoute函数里, 然后在createRouter函数里,将router实例传入generateRoute函数里进行添加路由并返回这个路由实例.但是问题是,调用服务端的接口需要用户的token,在createRouter里我无法获取用户的token.

**Comment by HcySunYang** [comment]
在 `createRouter` 里面可以获取到 `cookie`，所以应该是可以获取到 `token` 的。

**Comment by Wphilipp** [comment]
好的 谢谢
