### ISSUE TITLE
使用webpack-bundle-analyzer分析打包结果出错

### ISSUE THREAD

**Issue by bromiao** [shuidi-fed/vapper#94]
vue/cli3配置webpack-bundle-analyzer后，启动对应脚本yarn analyzer命令
1.控制台打印信息正常，浏览器能自动打开http://127.0.0.1:8888页面
![image](https://user-images.githubusercontent.com/19767083/84588623-a8794c00-ae5b-11ea-8304-3d2a6a89321d.png)
2.紧接着
![image](https://user-images.githubusercontent.com/19767083/84588638-c5158400-ae5b-11ea-846f-4c1a8fbc4028.png)
这似乎和webpack-bundle-analyzer实例化时机有关

附上webpack配置部分
![image](https://user-images.githubusercontent.com/19767083/84588672-22a9d080-ae5c-11ea-947e-4f1b700d70d4.png)

**Comment by cyyjs** [comment]
此配置会在client和server同时执行，所以会启动两次，可以在配置中增加环境判断解决。
例如：
```js
if (process.env.VAPPER_TARGET === 'client') {
 // webpack-bundle-analyzer code
}
```
